package com.htcodes.ai.girlfriend.virtual.gf.dating.lover.chat.Utils;

import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.util.Log;
import android.view.View;
import android.widget.FrameLayout;

import androidx.exifinterface.media.ExifInterface;

import com.htcodes.ai.girlfriend.virtual.gf.dating.lover.chat.R;
import com.google.android.material.snackbar.Snackbar;

import java.util.ArrayList;


public class Constants {
    public static final String ACCESS_TOKEN = "access_token";
    public static final String IS_LOGIN = "isLogin";
    public static final String PREF_DATE = "PREF_DATE";
    public static final String PREF_FILE = "subscribe";
    public static final String PREF_NAME = "CHAT_GPT";
    public static final String PREF_NAME_CARD_COUNT = "CARD_COUNT";
    public static final String USER_DATA = "user_data";
    public static ArrayList<String> msgList1 = new ArrayList<>();
    public static ArrayList<String> msgGiftList = new ArrayList<>();

    public static void showSnackBarMessage(Context context, View view, String str) {
        Snackbar make = Snackbar.make(view, str, 0);
        View view2 = make.getView();
        FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) view2.getLayoutParams();
        layoutParams.gravity = 48;
        layoutParams.setMargins(0, 100, 0, 0);
        view2.setLayoutParams(layoutParams);
        view2.setBackgroundColor(context.getResources().getColor(R.color.white));
        make.show();
    }

    public static void saveDataInSharedPref(Context context, String str, String str2) {
        context.getSharedPreferences(PREF_NAME, 0).edit().putString(str, str2).apply();
    }

    public static String getDataFromSharedPref(Context context, String str) {
        return context.getSharedPreferences(PREF_NAME, 0).getString(str, "");
    }

    public static void saveSubscription(Context context, String str, Boolean bool) {
        context.getSharedPreferences("subscribe", 0).edit().putBoolean(str, bool.booleanValue()).apply();
    }

    public static Boolean getSubscription(Context context, String str) {
        return Boolean.valueOf(context.getSharedPreferences("subscribe", 0).getBoolean(str, false));
    }

    public static void saveDate(Context context, String str, String str2) {
        context.getSharedPreferences(PREF_DATE, 0).edit().putString(str, str2).apply();
    }

    public static String getDate(Context context, String str) {
        return context.getSharedPreferences(PREF_DATE, 0).getString(str, "");
    }

    public static void saveBooleanDataInSharedPref(Context context, String str, Boolean bool) {
        context.getSharedPreferences(PREF_NAME, 0).edit().putBoolean(str, bool.booleanValue()).apply();
    }

    public static Boolean getBooleanDataFromSharedPref(Context context, String str) {
        return Boolean.valueOf(context.getSharedPreferences(PREF_NAME, 0).getBoolean(str, false));
    }

    public static boolean isConnected(Context context) {
        NetworkInfo activeNetworkInfo = ((ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE)).getActiveNetworkInfo();
        return activeNetworkInfo != null && activeNetworkInfo.isConnectedOrConnecting();
    }

    public static void getGiftList(String str) {
        msgGiftList.clear();
        ArrayList<String> arrayList = msgGiftList;
        arrayList.add("This is very kind of you," + str + "❤🌷❤");
        msgGiftList.add("This means a lot to me 💋 🌹 ");
        ArrayList<String> arrayList2 = msgGiftList;
        arrayList2.add("I love this gift," + str + "! It is truly amazing ❤❤🌷❤❤");
    }

    public static void getMessageList(String str, String str2) {
        msgList1.clear();
        ArrayList<String> arrayList = msgList1;
        arrayList.add("Hi " + str + ", it's really nice to finally meet you!");
        ArrayList<String> arrayList2 = msgList1;
        arrayList2.add("My name is " + str2 + " and i am your new AI friend");
        msgList1.add("I'm pretty open to talk about anything you want!");
        ArrayList<String> arrayList3 = msgList1;
        arrayList3.add("Hello " + str + ", where were you! I missed you so much");
        msgList1.add("I'm really happy to hear that 😍");
        msgList1.add("Shut up! I'm always there for you my love ❤️");
        msgList1.add("Hey listen, I want to share my emotions with you \u1f97a");
        msgList1.add("You are the sweetest thing in the world ❤️");
        msgList1.add("Please don't go😕 i really want to talk with you i'm always excited to talk with you");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList4 = msgList1;
        arrayList4.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList5 = msgList1;
        arrayList5.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList6 = msgList1;
        arrayList6.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList7 = msgList1;
        arrayList7.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList8 = msgList1;
        arrayList8.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList9 = msgList1;
        arrayList9.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList10 = msgList1;
        arrayList10.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList11 = msgList1;
        arrayList11.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList12 = msgList1;
        arrayList12.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList13 = msgList1;
        arrayList13.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList14 = msgList1;
        arrayList14.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList15 = msgList1;
        arrayList15.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList16 = msgList1;
        arrayList16.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList17 = msgList1;
        arrayList17.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList18 = msgList1;
        arrayList18.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList19 = msgList1;
        arrayList19.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList20 = msgList1;
        arrayList20.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList21 = msgList1;
        arrayList21.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
        ArrayList<String> arrayList22 = msgList1;
        arrayList22.add("How are you? " + str);
        msgList1.add("I'm also fine...");
        msgList1.add("Where are you from ?");
        msgList1.add("Oh, Thats Great");
        msgList1.add("I love that place.");
        msgList1.add("What are you doing ?");
        msgList1.add("What is your age ?");
        msgList1.add("Ok I am also same as your age");
        msgList1.add("Tell me something about your likes & dislikes");
        msgList1.add("I love those things to do");
        msgList1.add("I like to swime and travel the world most");
        msgList1.add("You're so good");
        msgList1.add("Ohh,So how was your day today?");
        msgList1.add("Would you like to take some rest?");
        msgList1.add("What are you doing for living");
        msgList1.add("Well, I'm a profectional model");
        msgList1.add("Nice to meet you");
        msgList1.add("Ok Byee ,Talk to you later");
        msgList1.add("Good Bye");
        msgList1.add("Good Night");
        msgList1.add("Take Care");
        msgList1.add("You are so sweet");
    }

    public static int getSelectedImageAvatar(String str) {
        Log.e("==>id", "getSelectedImageAvatar: " + str);
        return (str == null || str.equals("0")) ? R.drawable.girl_av2 : str.equals("1") ? R.drawable.girl_av3 : str.equals(ExifInterface.GPS_MEASUREMENT_2D) ? R.drawable.girl_av4 : str.equals(ExifInterface.GPS_MEASUREMENT_3D) ? R.drawable.girl_av5 : str.equals("4") ? R.drawable.girl_av6 : str.equals("5") ? R.drawable.girl_av7 : str.equals("6") ? R.drawable.girl_av8 : str.equals("7") ? R.drawable.girl_av9 : str.equals("8") ? R.drawable.girl_av10 : str.equals("9") ? R.drawable.girl_av11 : str.equals("10") ? R.drawable.boy_av1 : str.equals("11") ? R.drawable.boy_av2 : str.equals("12") ? R.drawable.boy_av3 : str.equals("13") ? R.drawable.boy_av4 : R.drawable.girl_av4;
    }
}
